
module.exports = {
	DB_USERS: 'users',
	DB_PIES_BEST: 'pies_best',
	DB_PIES_SEARCH: 'pies_search',

	USER_FLAG_PROPOSE_ROW: 1,
	USER_FLAG_PROPOSE_SEARCH: 2,

	STEP_NEW_USER: 0,
	STEP_NAME: 1,
	STEP_MAIN: 2,
	STEP_COMEBACK: 3,
	STEP_SEARCH: 4,
	STEP_SEARCH_BEGIN: 5,
	STEP_UNKNOWN: 6,
	STEP_NAME_RESULT: 7,

	PAYLOAD_MORE: 1,
	PAYLOAD_TWO_IN_ROW: 2,
	PAYLOAD_THREE_IN_ROW: 3,
};